services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aiv_support_portal
    ports:
      - "8092:8092"
    env_file:
      - .env
    environment:
      - VITE_BACKEND_API_URL=${VITE_BACKEND_API_URL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
